# Generated by Django 3.1.2 on 2021-03-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('fabric_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='product',
        ),
        migrations.RemoveField(
            model_name='store',
            name='provider',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='consumer',
            options={'verbose_name': 'Consumer', 'verbose_name_plural': 'Consumers'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'OrderProduct', 'verbose_name_plural': 'OrderProducts'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
