# Generated by Django 3.1.2 on 2021-03-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_shop', '0004_auto_20210301_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fabric_shop/static/fabric_shop/img/category'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
    ]
